"""dd description field to ategory

Revision ID: 935941c7b19f
Revises: 
Create Date: 2025-12-26 10:02:14.481785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935941c7b19f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
